= Setting Up an SSH Key for GitHub Access

When working with GitHub, setting up an SSH key can streamline your authentication process and provide a secure way to access your repositories. This tutorial will guide you through the steps required to create and add an SSH key to your GitHub account, allowing you to securely connect to GitHub repositories without the need for a username and password.

== the video

video::vGjwMOL70S4[youtube, width=640, height=480, align=left]

== the steps

=== 1 | Create an SSH Key

Create an SSH key by pasting this snippet into your terminal. Make sure to change the email address to the email associated with your GitHub account.

[source,bash]
-----
ssh-keygen -t ed25519 -C "your_email@example.com"
-----

=== 2 | Copy the SSH Key

In the previous step, you saved a file with a key on your computer. In order to copy the content of that file into your clipboard, run this command in your terminal.

[source,bash]
-----
pbcopy < ~/.ssh/id_ed25519.pub
-----

After running the command, press `Сtrl+V` to see if the content was copied.

=== 3 | Add your SSH Key to GitHub

Go to your GitHub account settings, create an SSH key, and paste the content. You can refer to the video for detailed instructions.

=== 4 | Test the SSH Connection

Try to clone a private repository using your SSH connection. Refer to the video for instructions. If the cloning process is successful, then you are all set.

== the links

https://docs.github.com/en/authentication/connecting-to-github-with-ssh[GitHub SSH Tutorial]
