= ArchLinux or Manjaro
:imagesdir: ../images
:figure-caption!:
:last-update-label!:

You are going to install all the necessary software using your Terminal,
Pacman package manager, and the AUR (Arch User Repository) Helper Yay.
Pacman should, by default, be installed on your system.

[arabic]
. Check if Pacman is installed by verifying its version:
+
[source,bash]
----
$ pacman --version 
----
+
You should have the following output:
+
[source,bash]
----
$ Pacman v6.0.2 - libalpm v13.0.2
----
+
`13.0.2` is the version; yours may be different.

. Update the list of known packages from the configured package
repositories online:
+
[source,bash]
----
$ sudo pacman -Syu
----
+
. Use Pacman to install the tools from the list below.
+
[cols=",",options="header",]
|===
|software |package_name
|Git |git
|Visual Studio Code |code
|Node.js |nodejs
|JDK 17 |jdk17-openjdk
|ANT |ant
|Maven |maven
|Netcat |gnu-netcat
|PostgreSQL 15 |postgresql
|Tomcat |tomcat10
|===
+
NOTE: By default, Git comes with most Linux distributions. To confirm if
Git is installed in your system, run the command `git --version` in your
terminal.
+
To install any application with Pacman, run:
+
[source,bash]
----
$ sudo pacman -S <package_name>
----
+
Where `<package_name>` identifies the software package you want to
install.
+
For example, to install Git, use the following command:
+
[source,bash]
----
$ sudo pacman -S git
----
+
Now run the `sudo pacman -S` command with every package name from the
table above.

. Use pacman to install `yay`:
+
[source,bash]
----
$ sudo pacman -S yay
----
+
Confirm the installation:
+
[source,bash]
----
$ sudo yay --version
----

. Use Yay to install the tools from the list below:
+
[cols=",",options="header",]
|===
|software |package_name
|Zoom |zoom
|Postman |postman-bin
|IntelliJ Idea |intellij-idea-ultimate-edition
|===
+
To install any application with Yay, run:
+
[source,bash]
----
$ sudo yay -S <package_name>
----
+
Where `<package_name>` identifies the software package you want to
install.
+
Run the `sudo yay -S` command with every package name from the table
above.

== Other Useful Commands

[source,bash]
----
$ pacman -Ss '^package_name'
----

Searches for the given string in package names that are available to
install via the Pacman package manager.

[source,bash]
----
$ pacman -Qs 'package_name'
----

Searches for already installed packages.

[source,bash]
----
$ pacman -Qi <package-name>
----

Shows information about a given package, already installed.

[source,bash]
----
$ pacman -Ql <package_name>
----

Lists all the files installed by the given package.

[source,bash]
----
$ pacman -Qo /path/to/file_name
----

Queries the database to know which package contains a given file.
